export const siteConfig = {
  title: 'Forge',
  titleLine1: 'Build anything.',
  titleLine2: 'Deploy anywhere.',
  contactEmail: 'hello@forge.studio',
  titleAlt: `Forge // Official Home Page`,
  logo: 'icons-logos-graphics/logos/Forge_Vector.svg',
  logoAlt: 'icons-logos-graphics/logos/forge-circle-black.png',
  description: 'A digital foundry for bold products, systems, and experiences.',
  navigation: [
    { label: 'Explore', href: '#explore' },
    { label: 'Process', href: '#process' },
    { label: 'Studio', href: '#studio' },
  ],
  marqueeItems: [
    { icon: 'applications', text: 'Applications' },
    { icon: 'cloud', text: 'Cloud Development' },
    { icon: 'devops', text: 'DevOps' },
    { icon: 'build', text: 'Build Projects' },
    { icon: 'pipeline', text: 'CI / CD Pipelines' },
    { icon: 'cloudformation', text: 'CloudFormation' },
    { icon: 'terraform', text: 'Terraform' },
    { icon: 'iac', text: 'Infrastructure as Code' },
  ],
  capabilities: [
    {
      index: '01',
      title: 'Product strategy',
      description: 'Shape the right problem, define the edge, and turn ambitious ideas into a buildable path.',
      tags: ['Direction', 'Research', 'Roadmaps'],
    },
    {
      index: '02',
      title: 'Digital products',
      description: 'Design expressive, useful interfaces and engineer them into fast, resilient applications.',
      tags: ['UX / UI', 'Web apps', 'Platforms'],
    },
    {
      index: '03',
      title: 'Intelligent systems',
      description: 'Connect data, automation, and AI into workflows that sharpen how teams operate.',
      tags: ['AI systems', 'Automation', 'Tooling'],
    },
  ],
  process: [
    { phase: 'Heat', detail: 'Find the signal. Strip the idea to what matters.' },
    { phase: 'Shape', detail: 'Prototype the experience and pressure-test the system.' },
    { phase: 'Strike', detail: 'Build with precision, ship with confidence, keep refining.' },
  ],
} as const;
